[project]
name = 'first-clarity-amm'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SPDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTKAKKR5V.sip013-semi-fungible-token-trait'
[contracts.constant-product-amm]
path = 'contracts/constant-product-amm.clar'
clarity_version = 2
epoch = 2.4

[contracts.constant-product-amm2]
path = 'contracts/constant-product-amm2.clar'
clarity_version = 2
epoch = 2.4

[contracts.cpm-lp-token]
path = 'contracts/cpm-lp-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.cpm2-lp-token]
path = 'contracts/cpm2-lp-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.test-coin1]
path = 'contracts/test-coin1.clar'
clarity_version = 2
epoch = 2.4

[contracts.test-coin2]
path = 'contracts/test-coin2.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
